Limit width of comment form on commit pages
refined-github/refined-github pull request #5035
Opened 2021-11-01 16:32 UTC by cheap-glitch

Fixes #5032 

## Test URLs
 * https://github.com/refined-github/refined-github/commit/fb7726a2335204d1cd33721b32b6e7b284c7397b

## Screenshot

**Before**

![screenshot-1635784246](https://user-images.githubusercontent.com/46634000/139706637-146eaa33-b689-427d-8af6-a9f1aeb3ada2.png)

**After**

![screenshot-1635784165](https://user-images.githubusercontent.com/46634000/139706635-578f018c-0c0a-439e-a084-36eecfa4d13d.png)

2021-11-01 16:35 UTC, cheap-glitch reviewed
![image](https://user-images.githubusercontent.com/46634000/139707019-3b638f1b-4bef-4637-9393-7e2ab9138c8c.png)

Now the subscription button looks kinda weird compared to the comments, should we "fix" it too?

2021-11-01 16:36 UTC, cheap-glitch reviewed
Test comment

2021-11-02 10:48 UTC, fregante requested changes
Let's add this CSS to our config and test it for a few days to ensure it doesn't conflict on other pages

2021-11-03 11:15 UTC, fregante approved these changes

2021-11-03 16:36 UTC, merged