Meta: Automatically generate release again
refined-github/refined-github pull request #5223
Opened 2021-12-17 11:14 UTC by fregante

For https://github.com/refined-github/refined-github/issues/4008#issuecomment-942723376

2021-12-17 11:18 UTC, FloEdelmann requested changes

2021-12-17 11:18 UTC, FloEdelmann commented on .github/workflows/release.yml
> +      - name: Create release
```suggestion
      - if: steps.daily-version.outputs.created
        name: Create release
```

2021-12-17 11:18 UTC, FloEdelmann commented on .github/workflows/release.yml
> +        uses: actions/github-script@v4.0.2
Let's use the newest version directly.

```suggestion
        uses: actions/github-script@v5.0.0
```

2021-12-19 17:25 UTC, merged

2021-12-22 19:07 UTC, fregante commented
This did not work: https://github.com/refined-github/refined-github/actions/runs/1607743677

2021-12-23 13:17 UTC, FloEdelmann commented
It's definitely the latter:

![grafik](https://user-images.githubusercontent.com/202916/147245986-545d40c0-a1ac-4883-82df-52f59a488d8d.png)

2021-12-23 13:18 UTC, FloEdelmann commented
Ahh, of course `steps.version.outputs.version` is empty, if the step is called `daily-version`...