Fix `clean-repo-sidebar` hiding some readme links
refined-github/refined-github pull request #5411
Opened 2022-02-15 11:49 UTC by cheap-glitch

Fixes https://github.com/refined-github/refined-github/issues/5410

## Test URLs

https://github.com/panva/jose

## Screenshot

TODO

2022-02-15 11:52 UTC, cheap-glitch commented on source/features/clean-repo-sidebar.css
> +	.rgh-clean-repo-sidebar .Layout-sidebar h2 [href$='/releases'] {
Probably not necessary, but just in case.

2022-02-15 13:40 UTC, yakov116 approved these changes
LGTM

2022-02-16 05:40 UTC, kidonng approved these changes
😅 I didn't realize `.rgh-clean-repo-sidebar` is applied to `body` instead of only the sidebar

2022-02-16 05:46 UTC, kidonng requested changes
Instead of selecting `.Layout-sidebar` manually, we should just add `.rgh-clean-repo-sidebar` to it.

That's what `sticky-sidebar` and `clean-conversation-sidebar` do and also the reason why I thought it that way

2022-02-16 09:40 UTC, cheap-glitch commented
> Instead of selecting `.Layout-sidebar` manually, we should just add `.rgh-clean-repo-sidebar` to it, not on the `body`.

I think we couldn't do it at the time because there was no simple selector for the sidebar. But now that we have `.Layout-sidebar`, I agree it makes more sense.

2022-02-16 10:05 UTC, kidonng commented
Also check `clean-repo-sidebar.tsx`:

https://github.com/refined-github/refined-github/blob/80e42b31dc33338d3ae12092d67fa8bc6f6d5161/source/features/clean-repo-sidebar.tsx#L59

2022-02-16 14:16 UTC, fregante approved these changes
Thanks for the PR and hotfix!

2022-02-16 14:40 UTC, merged