Shorten tree links outside of preview mode
refined-github/refined-github pull request #5464
Opened 2022-03-04 21:12 UTC by dnicolson

This pull request fixes tree links that do not shorten unless in preview mode. The solution is to call the `applyToLink` function on page load as well as on DOM changes.

I am not certain about removing the `.js-suggested-changes-blob` selector so it's entirely possible this breaks other things.

## Test URLs
https://github.com/refined-github/refined-github/pull/4759
https://github.com/dnicolson/x/issues/1

## Screenshot
Before:
![bad (1)](https://user-images.githubusercontent.com/2276355/156841128-2a4dc3c9-9df5-4220-8b84-5a68d0530ae6.gif)

After:
![good (1)](https://user-images.githubusercontent.com/2276355/156841132-2f336d61-b64f-4371-aa26-01218015294e.gif)

2022-03-04 23:44 UTC, kidonng commented
Did `shorten-links` break recently? Because I'm seeing #4758 again.

2022-03-05 07:23 UTC, fregante commented
> Because I'm seeing #4758 again.

I'm not on Safari, but I'm not on 22.3.3

<img width="660" alt="Screen Shot 20" src="https://user-images.githubusercontent.com/1402241/156873146-5f97357e-f477-4958-951e-e2961886294e.png">

2022-03-05 07:26 UTC, fregante commented
> Shorten tree links outside of preview mode

It works for me on your demo URL:

<img width="923" alt="Screen Shot 22" src="https://user-images.githubusercontent.com/1402241/156873215-99fd27c2-2977-42f9-99a7-d8a319b8431c.png">


An issue may exist when a comment is updated and we don't detect it. This piece of code has a long history (of bugs) so we need to be super careful when editing it.

2022-03-13 13:20 UTC, fregante commented on source/features/shorten-links.tsx
> +	for (const link of document.querySelectorAll('.comment-body a[href*="/tree/"]')) {
This already happens because `observe` automatically calls `add` on load, on every `a[href]`, which includes these.

2022-03-13 13:21 UTC, fregante approved these changes
I can merge this `isLinkInCode` extraction though

2022-03-13 13:39 UTC, fregante commented
Actually it needs to be updated preserving changes from https://github.com/refined-github/refined-github/pull/5472

2022-03-13 14:07 UTC, cheap-glitch requested changes
The bug is not caused by `shorten-links` but by `comments-time-machine-links`, which adds a query parameter to tree URLs, making this condition fail in `applyToLink`:

https://github.com/refined-github/shorten-repo-url/blob/a7c81316f438c38ce71b13309b974f0eb8c6838a/index.js#L239

Example here: https://github.com/refined-github/refined-github/issues/5479#issue-1166000758

2022-03-16 21:21 UTC, closed without merging