Stop triggering `select-all-notifications-shortcut` when typing
refined-github/refined-github pull request #5592
Opened 2022-04-12 13:56 UTC by cheap-glitch

Fixes the feature being triggered when typing in the search field :man_facepalming: 

## Test URLs

https://github.com/notifications

## Screenshot

https://user-images.githubusercontent.com/46634000/162978463-6add5495-704a-4683-bb7f-c15c0fae1726.mp4

2022-04-12 13:57 UTC, cheap-glitch commented on source/features/select-all-notifications-shortcut.tsx
> +		pageDetect.isBlank, // Empty notification list
This excludes every empty notification tabs ("Inbox", "Saved", etc.)

2022-04-13 05:27 UTC, fregante requested changes
This is why I'd rather have a helper that generates `data-hotkey` element.

If this is a bug, let's hotfix the feature for now and just use the code I suggested

2022-04-13 11:19 UTC, fregante commented on source/github-helpers/register-hotkey.tsx
> +		}
This won't throw
```suggestion
		hotkeyButton.remove();
```

2022-04-13 11:20 UTC, fregante approved these changes
✨

2022-04-13 13:32 UTC, merged