Less attention grabbing hint to draft a new release
refined-github/refined-github pull request #5854
Opened 2022-07-26 11:30 UTC by lode

Fixes https://github.com/refined-github/refined-github/issues/5851.

On merged PRs which are not (yet) part of a release a banner is shown to hint to create a release. This PR changes it from a banner & button, to regular text & link.

I also changed the wording a little, but if this is not wished it can be reversed of course. I did it can be confused for other forms of 'releasing', like deploying. I didn't remove the word 'release', just used other language to make it more understood as a noun.

I'm unsure about the conventions of html elements & classes. I borrowed a class from GitHub to make the text color a little more muted. Is that okay or should a RG class be made & used?

## Test URLs

It can be seen on any merged PR which is not part of a release. _Note that due to https://github.com/refined-github/refined-github/pull/5850, the banner/text isn't shown when the repository doesn't use releases at all._

Current example: https://github.com/refined-github/refined-github/pull/5850.

## Screenshot

![afbeelding](https://user-images.githubusercontent.com/511245/180747982-17d12405-7b89-40a8-999b-c002346a4594.png)

2022-07-26 14:31 UTC, fregante commented
It looks good, but I’m not sure the icon works there. Should we use .Btn-link on the A tag?

2022-07-26 17:27 UTC, lode commented
I can agree, the icon is a little weird for an inline link. I will remove.

Adding `.btn-link` causes a background-color when hovering, that's not really nice I think.

2022-07-31 08:10 UTC, fregante commented
Not a super fan of how it looks/aligns to be honest 😅 

<img width="684" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/182016517-faf1698d-e157-4286-a622-45857fbb774a.png">

_I added some spacing next to the link in my last commit_

2022-08-05 16:54 UTC, fregante requested changes
I think we should use the same style/alignment as the other two events visible in my screenshot, including the button (but no horizontal rule/line)

2022-08-08 19:37 UTC, lode commented
Yeah, good points. The inconsistency is also not nice, it becomes more busy if we add yet another style. Since it is not an event the banner styling is more correct. If I understand you correctly, we can just keep the styling as is, but remove the background color? (Like in the 'Pull request closed' banner, but then with the button and right-floating as currently.)

2022-08-09 02:24 UTC, fregante commented
I think we can reuse the whole markup I pasted. It's essentially the same concept:

- PR merged, delete fork?
- PR merged, create release?

Generally these two won't appear at the same time because people who send PRs from temporary forks aren't the same who can create a release. 

The same bubble style could also be ok for every usage in the feature though.

2022-08-28 17:46 UTC, lode commented
I'm not sure I understand. The screenshot you attached, looks the same as the current situation, doesn't it?

2022-08-28 18:16 UTC, fregante commented
> I'm not sure I understand. The screenshot you attached, looks the same as the current situation, doesn't it?

I'm talking about the "Pull request closed" style. It's true that it's similarly-sized, but it's not colored and it's what GitHub uses for a very similar intent: _You can do something now that the PR has been merged._

2022-08-28 18:16 UTC, fregante commented
Or like this, which I mentioned as an alternative:

<img width="639" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/187088736-e54b7cdf-5c25-4791-9a85-5b2128a19b1d.png">

2022-08-28 21:00 UTC, lode commented
Ah, I understand.

Some thoughts I have about these:

- The PR closed, delete the fork style: it does worry me a little that there is a chance both banners would be shown at the same time, and then the speech bubble is a bit weird.
- The alternative deleted branch style: it doesn't feel correct, since that is about an event placed on the timeline, which this is not.

I'm more inclined to keep the same situation as now, but with a transparent instead of a blue background. This:

- keeps the styling similar to how it is now, not changing too much for current users
- keeps the styling in sync with the first-appeared-in banner, which is nice I think
- gives it less attention, just like GH decided upon for the delete fork banner with similar intent

Although, thinking about the last point. Deleting a fork is less important than drafting a release. So maybe the extra attention is worth it. I'm also fine closing this PR. I think it was good that the banner was removed if a repo doesn't have releases at all, with that this might be good as is.

2022-08-29 03:39 UTC, fregante commented
> both banners would be shown at the same time, 

Super rare. People who can release a new versions don't generally use forks. If they do, that's their own issue 😃 

> that is about an event placed on the timeline, which this is not.

I agree, that's why the bubble works, exactly like GitHub is doing.

2022-09-25 09:41 UTC, fregante commented
Feel free to send a new PR

2022-09-25 09:41 UTC, closed without merging