Creating rgh-linkify-yolo-issues feature
refined-github/refined-github pull request #6269
Opened 2023-01-31 10:23 UTC by hemantsoni42

this code will replace the original text content with an anchor element
In previous pull request the file name is rgh-linkify-yolo-issues.js which fails in some checks that why in this the file name is renamed as rgh-linkify-yolo-issues.tsx 
Closes #6258

## Test URLs

## Screenshot

2023-01-31 10:33 UTC, fregante requested changes
Thank you for the PR, unfortunately this is missing a lot of work for now.

Please refer to the existing features, there's a complete documentation in the contributing.md file. Also there are several issues in the code:

- I suggested using JSX, `wrap` and `select`, instead of `createElement` and `appendChild` and `querySelectorAll`. Please copy the snippet of code I gave you because it was 90% valid
- the `td:nth-child` selector is way too broad, it must be limited to the specific table. This is the 10% that was missing.
- This file is missing `features.add` and all the logic around it, look at `rgh-linkify-features` for example
- Make sure you build and run the extension locally before submitting. For example here the tests are failing and this file is not loaded at all because it's not imported in `refined-github.ts

2023-02-01 05:30 UTC, hemantsoni42 commented
Thank you sir for all your support and guidance.
Currently this newly added file is not showing any error in local machine. If I will not satisfies your goal please let me know and thank you once again.

2023-02-01 05:33 UTC, fregante requested changes
Please run the extension locally, ensure that `npm test` completes successfully and _only then_ push your changes and ask for a review. As is, this does not work.

Make sure it works and include a screenshot on the next push please.

2023-02-01 05:33 UTC, fregante commented on rgh-linkify-yolo-issues.tsx
> +	for (const issueCell of select.all("table-selector td:nth-child(2)")) {
What's `table-selector`? This PR hasn't been tested. Test before marking as "ready"

2023-02-01 05:33 UTC, fregante commented on rgh-linkify-yolo-issues.tsx
> +		pageDetect.isIssue,
All completely unrelated. Please don't copy-paste blindly, each line in the file must make sense

2023-02-01 05:33 UTC, fregante commented on rgh-linkify-yolo-issues.tsx
> +	url: import.meta.url,
Completely invalid usage

2023-02-01 05:49 UTC, fregante commented
> this file is not loaded at all because it's not imported in `refined-github.ts`

2023-02-01 05:49 UTC, fregante commented
Sorry I don’t think you can submit further changes here

2023-02-01 05:49 UTC, closed without merging