fix: do not fuzzy match author name
refined-github/refined-github pull request #6857
Opened 2023-08-26 11:16 UTC by scarf005

-fixes #6856 

## Test URLs

<https://github.com/cataclysmbnteam/Cataclysm-BN/pulls?q=is%3Apr+author%3Aborsek+sort%3Aupdated-desc>

## Screenshot

![image](https://github.com/refined-github/refined-github/assets/54838975/a5bb79b0-e37c-4287-a955-c527ef18c7fd)

2023-08-26 19:20 UTC, fregante requested changes
Thanks for the PR

The title is not just that, this selector won't match anything, I think. 

What about $=

2023-08-26 23:54 UTC, scarf005 commented
![image](https://github.com/refined-github/refined-github/assets/54838975/35a0e517-a954-42e6-ba25-9e16acd01984)
...oh, missed that.

2023-08-27 07:00 UTC, fregante approved these changes

2023-08-27 14:43 UTC, yakov116 approved these changes

2023-08-27 18:08 UTC, merged