fix(mark-merge-commits-in-list): update selector
refined-github/refined-github pull request #7087
Opened 2023-11-22 10:09 UTC by kovsu

close: #7003

2023-11-22 10:09 UTC, kovsu commented
after:
![image](https://github.com/refined-github/refined-github/assets/82451257/34a7e901-2bb9-4fff-876a-19b7a76fc837)

2023-11-22 10:11 UTC, fregante commented
Thank you! Can you also look at `dim-bots`?

- https://github.com/refined-github/refined-github/issues/7068

2023-11-22 10:16 UTC, fregante requested changes
So I think here (and maybe in the other PR) it can be greatly simplified. Most likely you don't need a `isLegacy` check:

- query `'.markdown-title a, a.markdown-title'` in the same function. The right element will be selected in both cases.
- add `.listviewitem` to the `$$()` array

I think that's about it, here. In the other feature `isLegacy` is still needed for the `flex-wrap` addition I think

This change is particularly necessary because the old view isn't really legacy, I just noticed that `isPRCommits` still uses it: https://github.com/refined-github/refined-github/pull/7087/commits

2023-11-22 10:17 UTC, fregante commented on source/features/mark-merge-commits-in-list.tsx
>  	return $('a.markdown-title', commit)!.pathname.split('/').pop()!;
```suggestion
	return $([
		'a.markdown-title', // Old view style (before November 2023)
		'.markdown-title a',
	], commit)!.pathname.split('/').pop()!;
```

You can use array to comment on each selector

2023-11-22 11:07 UTC, kovsu commented
> So I think here ~(and maybe in the other PR)~ it can be greatly simplified. Most likely you don't need a `isLegacy` check:
> 
> * query `'.markdown-title a, a.markdown-title'` in the same function. The right element will be selected in both cases.
> * add `.listviewitem` to the `$$()` array
> 
> I think that's about it, here. In the other feature `isLegacy` is still needed for the `flex-wrap` addition I think
> 
> This change is particularly necessary because the old view isn't really legacy, I just noticed that `isPRCommits` still uses it: [#7087 (commits)](https://github.com/refined-github/refined-github/pull/7087/commits)

I haven't used `select-dom` before. I will check it.

2023-11-22 11:41 UTC, fregante approved these changes

2023-11-22 11:42 UTC, kovsu commented
Should I update the other PR?

2023-11-22 11:48 UTC, fregante commented
Already done 😃

2023-11-23 05:28 UTC, fregante commented
## Updated screenshot

![Screenshot 3](https://github.com/refined-github/refined-github/assets/1402241/9bdbc938-69c4-4692-8d47-11e30676de62)

2023-11-23 05:31 UTC, merged

2023-11-23 05:32 UTC, fregante commented
If you'd like, it'd be good to fix the TODO in this file. You can see how it's used in other features

2023-11-23 06:32 UTC, kovsu commented
like this? @fregante
![image](https://github.com/refined-github/refined-github/assets/82451257/38df3e51-cf08-435e-899b-58ae899a5cb4)

2023-11-23 07:05 UTC, fregante commented
Yes I think so ☺️ 

You can also drop the `duplicate` key