`use-first-commit-message-for-new-prs`: do not replace title on page reload
refined-github/refined-github pull request #7198
Opened 2023-12-31 16:59 UTC by pgimalac

Closes https://github.com/refined-github/refined-github/issues/7191.

Do not set the title to the first commit message on page reload.
It avoids overwriting user input.

The feature still works on page `load`, but not on `reload`, github just restores whatever input was before, whether the first commit title or user input.

## Test URLs
https://github.com/pgimalac/refined-github/compare/main...pgimalac:refined-github:pgimalac/fit-rendered-markdown?expand=1

## Screenshot

https://github.com/refined-github/refined-github/assets/23154723/8d70e4e2-560c-4363-bc19-d5bd8d0ca1d3

2024-01-10 05:33 UTC, fregante commented
I'd be more comfortable targeting this specific GitHub behavior rather than guess the user action. It seems to be easy at this point, assuming that our code runs before Github's `session:resume` event:

```js
function into () {
  if (sessionStorage.getItem(`session-resume:/${getRepo()?.nameWithOwner}/compare`)) {
	  return false;
  }
  
  // …
}
```

2024-01-10 05:33 UTC, fregante requested changes
I'd be more comfortable targeting this specific GitHub behavior rather than guess the user action. It seems to be easy at this point, assuming that our code runs before Github's `session:resume` event:

```js
function into () {
  if (sessionStorage.getItem(`session-resume:/${getRepo()?.nameWithOwner}/compare`)) {
	  return false;
  }
  
  // …
}
```

2024-01-21 10:50 UTC, pgimalac commented
Hey @fregante, sorry for the delay, I gave it a try but it doesn't work, the code runs before the field is reloaded (the title is the branch name, which is the default) but there is no `session-resume` in the `sessionStorage`...

2024-01-21 10:52 UTC, fregante commented
session:resume is an event on window. Look into this repo to find how to use it

2024-01-21 11:38 UTC, pgimalac commented
> session:resume is an event on window. Either way we don't need to do anything about it

I'm not sure I understand, do you want me to do anything about this PR then ?

2024-01-21 17:25 UTC, fregante commented
> do you want me to do anything about this PR then ?

I posted the piece of code I'd like to see inside `init`. Does that fix the issue? In my manual tests it worked

2024-01-22 09:10 UTC, pgimalac commented
> Hey @fregante, sorry for the delay, I gave it a try but it doesn't work, the code runs before the field is reloaded (the title is the branch name, which is the default) but there is no session-resume in the sessionStorage...

As I said in my previous message I tried replacing the block I added with the one you wrote using `session-resume`, but it didn't work. I printed all `sessionStorage` key/value and none were `session-resume`...
It worked for you ?

2024-02-02 05:22 UTC, closed without merging